name: CI

on:
  push:
    paths-ignore: [ man/**, conf/**, docs/**, README.md, LICENSE, .gitignore ]
  pull_request:
    paths-ignore: [ man/**, conf/**, docs/**, README.md, LICENSE, .gitignore ]

env:
  CARGO_TERM_COLOR: always
  # Emit backtraces on panics.
  RUST_BACKTRACE: full

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        rust: [1.43, stable, beta, nightly]
        os: [ubuntu-20.04, macos-10.15]

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Update CI
      if: matrix.os == 'ubuntu-20.04'
      run: sudo apt update
    - name: Install dependency
      if: matrix.os == 'ubuntu-20.04'
      run: sudo apt install libpam0g-dev libsystemd-dev
    - uses: actions-rs/toolchain@v1.0.7
      with:
        profile: minimal
        toolchain: ${{ matrix.rust }}
    - name: Run ubuntu cargo build
      if: matrix.os == 'ubuntu-20.04'
      uses: actions-rs/cargo@v1.0.3
      with:
        command: build
        args: --release --all-targets --all-features --verbose
    - name: Run macOS cargo build
      if: matrix.os == 'macos-10.15'
      uses: actions-rs/cargo@v1.0.3
      with:
        command: build
        args: --release --all-targets --all-features --verbose
    - name: Run ubuntu cargo tests
      if: matrix.os == 'ubuntu-20.04'
      uses: actions-rs/cargo@v1.0.3
      with:
        command: test
        args: --release --all-targets --all-features --verbose
    - name: Run macos cargo tests
      if: matrix.os == 'macos-10.15'
      uses: actions-rs/cargo@v1.0.3
      with:
        command: test
        args: --release --all-targets --all-features --verbose
