name: Audit

on:
  push:
    paths: [Cargo.lock, Cargo.toml]
  pull_request:
    paths: [Cargo.lock, Cargo.toml]
  schedule:
  - cron: "0 2 * * 1-5"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Audit dependency
      run: cargo audit
